#!/usr/bin/env python3

import argparse
import glob
import shutil
import re
import os

def get_directories(dir_path='.'):
    dirs = set()
    with os.scandir(dir_path) as it:
        for entry in it:
            if entry.is_dir():
                dirs.add(entry.name)
    return dirs

def sort_folder(dir_path='.'):
    os.chdir(dir_path)
    date_regex = r'^\d{4}-\d{2}-\d{2}\.md$'
    mds = glob.glob('*.md')
    for md in mds:
        if re.match(date_regex, md):
            name, _ = md.split('.')
            year, month, _ = name.split('-')
            path = f"{year}/{month}"
            if year not in get_directories():
                os.mkdir(year)
            if month not in get_directories(year):
                os.mkdir(path)
            shutil.move(md, path)

parser = argparse.ArgumentParser(description='Organize obsidian daily markdown files into subfolders by year and month')
parser.add_argument('-p', '--path', default='/Users/guarnit/Desktop/Notes', help='absolute path of directory to organize')
args = parser.parse_args()
sort_folder(args.path)
